export const userActiontypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_USER_FRIENDS: "SET_CURRENT_USER_FRIENDS",
  SET_CURRENT_USER_MESSAGES: "SET_CURRENT_USER_MESSAGES",
  SET_CURRENT_RECIVER_ID: "SET_CURRENT_RECIVER_ID",
  SET_FETCHING_STATE: "SET_FETCHING_STATE",
};
